/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.threed.demo.model.impl;

/**
 * Basic interface for {@link #ASSEMBLY_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface AssemblyBase extends com.top_logic.threed.demo.model.Node {

	/**
	 * Name of type <code>Assembly</code>
	 */
	String ASSEMBLY_TYPE = "Assembly";

	/**
	 * Getter for part {@link #CHILDREN_ATTR}.
	 */
	@Override
	@SuppressWarnings("unchecked")
	default java.util.List<? extends com.top_logic.threed.demo.model.Node> getChildren() {
		return (java.util.List<? extends com.top_logic.threed.demo.model.Node>) tValueByName(CHILDREN_ATTR);
	}

}
