/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.threed.demo.model.impl;

/**
 * Basic interface for {@link #ASSET_COLLECTION_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface AssetCollectionBase extends com.top_logic.model.TLObject {

	/**
	 * Name of type <code>AssetCollection</code>
	 */
	String ASSET_COLLECTION_TYPE = "AssetCollection";

	/**
	 * Part <code>assets</code> of <code>AssetCollection</code>
	 * 
	 * <p>
	 * Declared as <code>tl.threed.demo:Asset3D</code> in configuration.
	 * </p>
	 */
	String ASSETS_ATTR = "assets";

	/**
	 * Part <code>subFolders</code> of <code>AssetCollection</code>
	 * 
	 * <p>
	 * Declared as <code>tl.threed.demo:AssetFolder</code> in configuration.
	 * </p>
	 */
	String SUB_FOLDERS_ATTR = "subFolders";

	/**
	 * Getter for part {@link #ASSETS_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.threed.demo.model.Asset3D> getAssets() {
		return (java.util.Set<? extends com.top_logic.threed.demo.model.Asset3D>) tValueByName(ASSETS_ATTR);
	}

	/**
	 * Live view of the {@link #ASSETS_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.Set<com.top_logic.threed.demo.model.Asset3D> getAssetsModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(ASSETS_ATTR);
		@SuppressWarnings("unchecked")
		java.util.Set<com.top_logic.threed.demo.model.Asset3D> result = (java.util.Set<com.top_logic.threed.demo.model.Asset3D>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #ASSETS_ATTR}.
	 */
	default void setAssets(java.util.Set<com.top_logic.threed.demo.model.Asset3D> newValue) {
		tUpdateByName(ASSETS_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #ASSETS_ATTR} reference.
	 */
	default void addAsset(com.top_logic.threed.demo.model.Asset3D newValue) {
		tAddByName(ASSETS_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #ASSETS_ATTR} reference.
	 */
	default void removeAsset(com.top_logic.threed.demo.model.Asset3D oldValue) {
		tRemoveByName(ASSETS_ATTR, oldValue);
	}

	/**
	 * Getter for part {@link #SUB_FOLDERS_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<? extends com.top_logic.threed.demo.model.AssetFolder> getSubFolders() {
		return (java.util.Set<? extends com.top_logic.threed.demo.model.AssetFolder>) tValueByName(SUB_FOLDERS_ATTR);
	}

	/**
	 * Live view of the {@link #SUB_FOLDERS_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.Set<com.top_logic.threed.demo.model.AssetFolder> getSubFoldersModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(SUB_FOLDERS_ATTR);
		@SuppressWarnings("unchecked")
		java.util.Set<com.top_logic.threed.demo.model.AssetFolder> result = (java.util.Set<com.top_logic.threed.demo.model.AssetFolder>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #SUB_FOLDERS_ATTR}.
	 */
	default void setSubFolders(java.util.Set<com.top_logic.threed.demo.model.AssetFolder> newValue) {
		tUpdateByName(SUB_FOLDERS_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #SUB_FOLDERS_ATTR} reference.
	 */
	default void addSubFolder(com.top_logic.threed.demo.model.AssetFolder newValue) {
		tAddByName(SUB_FOLDERS_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #SUB_FOLDERS_ATTR} reference.
	 */
	default void removeSubFolder(com.top_logic.threed.demo.model.AssetFolder oldValue) {
		tRemoveByName(SUB_FOLDERS_ATTR, oldValue);
	}

}
