/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.threed.demo.model.impl;

import com.top_logic.knowledge.objects.KnowledgeObject;

/**
 * Wrapper implementation class for <code>tl.threed.demo:Asset3D</code> business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.ImplementationTemplateGenerator}
 */
public class Asset3DImpl extends com.top_logic.element.structured.wrap.AttributedStructuredElementWrapper implements com.top_logic.threed.demo.model.Asset3D {

	/**
	 * Default constructor.
	 */
	public Asset3DImpl(KnowledgeObject ko) {
		super(ko);
	}

}
