/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.threed.demo.model.impl;

/**
 * Basic interface for {@link #ASSET3D_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface Asset3DBase extends com.top_logic.model.TLNamed {

	/**
	 * Name of type <code>Asset3D</code>
	 */
	String ASSET3D_TYPE = "Asset3D";

	/**
	 * Part <code>gltfUrl</code> of <code>Asset3D</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String GLTF_URL_ATTR = "gltfUrl";

	/**
	 * Part <code>jtFile</code> of <code>Asset3D</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String JT_FILE_ATTR = "jtFile";

	/**
	 * Part <code>layoutPoint</code> of <code>Asset3D</code>
	 * 
	 * <p>
	 * Declared as <code>tl.threed.demo:ConnectionPoint</code> in configuration.
	 * </p>
	 */
	String LAYOUT_POINT_ATTR = "layoutPoint";

	/**
	 * Part <code>name</code> of <code>Asset3D</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

	/**
	 * Part <code>snappingPoints</code> of <code>Asset3D</code>
	 * 
	 * <p>
	 * Declared as <code>tl.threed.demo:ConnectionPoint</code> in configuration.
	 * </p>
	 */
	String SNAPPING_POINTS_ATTR = "snappingPoints";

	/**
	 * Getter for part {@link #GLTF_URL_ATTR}.
	 */
	default String getGltfUrl() {
		return (String) tValueByName(GLTF_URL_ATTR);
	}

	/**
	 * Getter for part {@link #JT_FILE_ATTR}.
	 */
	default String getJtFile() {
		return (String) tValueByName(JT_FILE_ATTR);
	}

	/**
	 * Setter for part {@link #JT_FILE_ATTR}.
	 */
	default void setJtFile(String newValue) {
		tUpdateByName(JT_FILE_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #LAYOUT_POINT_ATTR}.
	 */
	default com.top_logic.threed.demo.model.ConnectionPoint getLayoutPoint() {
		return (com.top_logic.threed.demo.model.ConnectionPoint) tValueByName(LAYOUT_POINT_ATTR);
	}

	/**
	 * Setter for part {@link #LAYOUT_POINT_ATTR}.
	 */
	default void setLayoutPoint(com.top_logic.threed.demo.model.ConnectionPoint newValue) {
		tUpdateByName(LAYOUT_POINT_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #SNAPPING_POINTS_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.List<? extends com.top_logic.threed.demo.model.ConnectionPoint> getSnappingPoints() {
		return (java.util.List<? extends com.top_logic.threed.demo.model.ConnectionPoint>) tValueByName(SNAPPING_POINTS_ATTR);
	}

	/**
	 * Live view of the {@link #SNAPPING_POINTS_ATTR} part.
	 * <p>
	 * Changes to this {@link java.util.Collection} change directly the attribute value.
	 * The caller has to take care of the transaction handling.
	 * </p>
	 */
	default java.util.List<com.top_logic.threed.demo.model.ConnectionPoint> getSnappingPointsModifiable() {
		com.top_logic.model.TLStructuredTypePart attribute = tType().getPart(SNAPPING_POINTS_ATTR);
		@SuppressWarnings("unchecked")
		java.util.List<com.top_logic.threed.demo.model.ConnectionPoint> result = (java.util.List<com.top_logic.threed.demo.model.ConnectionPoint>) com.top_logic.element.meta.kbbased.WrapperMetaAttributeUtil.getLiveCollection(this, attribute);
		return result;
	}

	/**
	 * Setter for part {@link #SNAPPING_POINTS_ATTR}.
	 */
	default void setSnappingPoints(java.util.List<com.top_logic.threed.demo.model.ConnectionPoint> newValue) {
		tUpdateByName(SNAPPING_POINTS_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #SNAPPING_POINTS_ATTR} reference.
	 */
	default void addSnappingPoint(com.top_logic.threed.demo.model.ConnectionPoint newValue) {
		tAddByName(SNAPPING_POINTS_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #SNAPPING_POINTS_ATTR} reference.
	 */
	default void removeSnappingPoint(com.top_logic.threed.demo.model.ConnectionPoint oldValue) {
		tRemoveByName(SNAPPING_POINTS_ATTR, oldValue);
	}

}
