/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.threed.demo.model.impl;

/**
 * Basic interface for {@link #ASSET_CATALOGUE_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface AssetCatalogueBase extends com.top_logic.threed.demo.model.AssetCollection {

	/**
	 * Name of type <code>AssetCatalogue</code>
	 */
	String ASSET_CATALOGUE_TYPE = "AssetCatalogue";

}
