/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.threed.demo.model.impl;

/**
 * Basic interface for {@link #ASSET_FOLDER_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface AssetFolderBase extends com.top_logic.threed.demo.model.AssetCollection, com.top_logic.model.TLNamed {

	/**
	 * Name of type <code>AssetFolder</code>
	 */
	String ASSET_FOLDER_TYPE = "AssetFolder";

	/**
	 * Part <code>name</code> of <code>AssetFolder</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

}
