/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.threed.demo.model.impl;

/**
 * Basic interface for {@link #CONNECTION_POINT_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ConnectionPointBase extends com.top_logic.model.TLObject {

	/**
	 * Name of type <code>ConnectionPoint</code>
	 */
	String CONNECTION_POINT_TYPE = "ConnectionPoint";

	/**
	 * Part <code>classifiers</code> of <code>ConnectionPoint</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String CLASSIFIERS_ATTR = "classifiers";

	/**
	 * Part <code>tx</code> of <code>ConnectionPoint</code>
	 * 
	 * <p>
	 * Declared as <code>tl.threed.core:Transformation</code> in configuration.
	 * </p>
	 */
	String TX_ATTR = "tx";

	/**
	 * Getter for part {@link #CLASSIFIERS_ATTR}.
	 */
	@SuppressWarnings("unchecked")
	default java.util.Set<String> getClassifiers() {
		return (java.util.Set<String>) tValueByName(CLASSIFIERS_ATTR);
	}

	/**
	 * Setter for part {@link #CLASSIFIERS_ATTR}.
	 */
	default void setClassifiers(java.util.Set<String> newValue) {
		tUpdateByName(CLASSIFIERS_ATTR, newValue);
	}

	/**
	 * Adds a value to the {@link #CLASSIFIERS_ATTR} reference.
	 */
	default void addClassifier(String newValue) {
		tAddByName(CLASSIFIERS_ATTR, newValue);
	}

	/**
	 * Removes the given value from the {@link #CLASSIFIERS_ATTR} reference.
	 */
	default void removeClassifier(String oldValue) {
		tRemoveByName(CLASSIFIERS_ATTR, oldValue);
	}

	/**
	 * Getter for part {@link #TX_ATTR}.
	 */
	default com.top_logic.threed.core.math.Transformation getTx() {
		return (com.top_logic.threed.core.math.Transformation) tValueByName(TX_ATTR);
	}

	/**
	 * Setter for part {@link #TX_ATTR}.
	 */
	default void setTx(com.top_logic.threed.core.math.Transformation newValue) {
		tUpdateByName(TX_ATTR, newValue);
	}

}
