/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.threed.demo.model.impl;

/**
 * Basic interface for {@link #NODE_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface NodeBase extends com.top_logic.threed.demo.model.ScenePart {

	/**
	 * Name of type <code>Node</code>
	 */
	String NODE_TYPE = "Node";

	/**
	 * Part <code>asset</code> of <code>Node</code>
	 * 
	 * <p>
	 * Declared as <code>tl.threed.demo:Asset3D</code> in configuration.
	 * </p>
	 */
	String ASSET_ATTR = "asset";

	/**
	 * Part <code>color</code> of <code>Node</code>
	 * 
	 * <p>
	 * Declared as <code>tl.util:Color</code> in configuration.
	 * </p>
	 */
	String COLOR_ATTR = "color";

	/**
	 * Part <code>immutable</code> of <code>Node</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Boolean</code> in configuration.
	 * </p>
	 */
	String IMMUTABLE_ATTR = "immutable";

	/**
	 * Part <code>jtFile</code> of <code>Node</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String JT_FILE_ATTR = "jtFile";

	/**
	 * Part <code>layer</code> of <code>Node</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Boolean</code> in configuration.
	 * </p>
	 */
	String LAYER_ATTR = "layer";

	/**
	 * Part <code>name</code> of <code>Node</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

	/**
	 * Part <code>tile</code> of <code>Node</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Boolean</code> in configuration.
	 * </p>
	 */
	String TILE_ATTR = "tile";

	/**
	 * Part <code>tx</code> of <code>Node</code>
	 * 
	 * <p>
	 * Declared as <code>tl.threed.core:Transformation</code> in configuration.
	 * </p>
	 */
	String TX_ATTR = "tx";

	/**
	 * Getter for part {@link #ASSET_ATTR}.
	 */
	default com.top_logic.threed.demo.model.Asset3D getAsset() {
		return (com.top_logic.threed.demo.model.Asset3D) tValueByName(ASSET_ATTR);
	}

	/**
	 * Setter for part {@link #ASSET_ATTR}.
	 */
	default void setAsset(com.top_logic.threed.demo.model.Asset3D newValue) {
		tUpdateByName(ASSET_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #COLOR_ATTR}.
	 */
	default java.awt.Color getColor() {
		return (java.awt.Color) tValueByName(COLOR_ATTR);
	}

	/**
	 * Setter for part {@link #COLOR_ATTR}.
	 */
	default void setColor(java.awt.Color newValue) {
		tUpdateByName(COLOR_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #IMMUTABLE_ATTR}.
	 */
	default boolean getImmutable() {
		return (Boolean) tValueByName(IMMUTABLE_ATTR);
	}

	/**
	 * Setter for part {@link #IMMUTABLE_ATTR}.
	 */
	default void setImmutable(boolean newValue) {
		tUpdateByName(IMMUTABLE_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #JT_FILE_ATTR}.
	 */
	default String getJtFile() {
		return (String) tValueByName(JT_FILE_ATTR);
	}

	/**
	 * Getter for part {@link #LAYER_ATTR}.
	 */
	default boolean getLayer() {
		return (Boolean) tValueByName(LAYER_ATTR);
	}

	/**
	 * Setter for part {@link #LAYER_ATTR}.
	 */
	default void setLayer(boolean newValue) {
		tUpdateByName(LAYER_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #TILE_ATTR}.
	 */
	default boolean getTile() {
		return (Boolean) tValueByName(TILE_ATTR);
	}

	/**
	 * Setter for part {@link #TILE_ATTR}.
	 */
	default void setTile(boolean newValue) {
		tUpdateByName(TILE_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #TX_ATTR}.
	 */
	default com.top_logic.threed.core.math.Transformation getTx() {
		return (com.top_logic.threed.core.math.Transformation) tValueByName(TX_ATTR);
	}

	/**
	 * Setter for part {@link #TX_ATTR}.
	 */
	default void setTx(com.top_logic.threed.core.math.Transformation newValue) {
		tUpdateByName(TX_ATTR, newValue);
	}

}
