/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.threed.demo.model.impl;

/**
 * Basic interface for {@link #SCENE_PART_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface ScenePartBase extends com.top_logic.element.structured.StructuredElement {

	/**
	 * Name of type <code>ScenePart</code>
	 */
	String SCENE_PART_TYPE = "ScenePart";

}
