/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.threed.demo.model.impl;

/**
 * Basic interface for {@link #SCENE_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface SceneBase extends com.top_logic.threed.demo.model.ScenePart {

	/**
	 * Name of type <code>Scene</code>
	 */
	String SCENE_TYPE = "Scene";

	/**
	 * Part <code>name</code> of <code>Scene</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:String</code> in configuration.
	 * </p>
	 */
	String NAME_ATTR = "name";

	/**
	 * Part <code>rootNode</code> of <code>Scene</code>
	 * 
	 * <p>
	 * Declared as <code>tl.threed.demo:Node</code> in configuration.
	 * </p>
	 */
	String ROOT_NODE_ATTR = "rootNode";

	/**
	 * Getter for part {@link #ROOT_NODE_ATTR}.
	 */
	default com.top_logic.threed.demo.model.Node getRootNode() {
		return (com.top_logic.threed.demo.model.Node) tValueByName(ROOT_NODE_ATTR);
	}

	/**
	 * Setter for part {@link #ROOT_NODE_ATTR}.
	 */
	default void setRootNode(com.top_logic.threed.demo.model.Node newValue) {
		tUpdateByName(ROOT_NODE_ATTR, newValue);
	}

}
