/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.threed.demo.model.impl;

/**
 * Basic interface for {@link #TEXT_TYPE} business objects.
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.InterfaceGenerator}
 */
public interface TextBase extends com.top_logic.threed.demo.model.Node {

	/**
	 * Name of type <code>Text</code>
	 */
	String TEXT_TYPE = "Text";

	/**
	 * Part <code>background</code> of <code>Text</code>
	 * 
	 * <p>
	 * Declared as <code>tl.util:Color</code> in configuration.
	 * </p>
	 */
	String BACKGROUND_ATTR = "background";

	/**
	 * Part <code>fontSize</code> of <code>Text</code>
	 * 
	 * <p>
	 * Declared as <code>tl.core:Integer</code> in configuration.
	 * </p>
	 */
	String FONT_SIZE_ATTR = "fontSize";

	/**
	 * Getter for part {@link #BACKGROUND_ATTR}.
	 */
	default java.awt.Color getBackground() {
		return (java.awt.Color) tValueByName(BACKGROUND_ATTR);
	}

	/**
	 * Setter for part {@link #BACKGROUND_ATTR}.
	 */
	default void setBackground(java.awt.Color newValue) {
		tUpdateByName(BACKGROUND_ATTR, newValue);
	}

	/**
	 * Getter for part {@link #COLOR_ATTR}.
	 */
	@Override
	default java.awt.Color getColor() {
		return (java.awt.Color) tValueByName(COLOR_ATTR);
	}

	/**
	 * Getter for part {@link #FONT_SIZE_ATTR}.
	 */
	default Integer getFontSize() {
		return (Integer) tValueByName(FONT_SIZE_ATTR);
	}

	/**
	 * Setter for part {@link #FONT_SIZE_ATTR}.
	 */
	default void setFontSize(Integer newValue) {
		tUpdateByName(FONT_SIZE_ATTR, newValue);
	}

}
