/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.threed.demo.model;

/**
 * Factory for <code>tl.threed.demo</code> objects.
 * 
 * <p>
 * Note: this is generated code. Do not modify. Instead, create a subclass and register this in the module system.
 * </p>
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.FactoryGenerator}
 */
public class TlThreedDemoFactory extends com.top_logic.element.structured.wrap.StructuredElementWrapperFactory {

	/**
	 * Name of singleton {@link #TL_THREED_DEMO_STRUCTURE}.
	 */
	public static final String SINGLETON_CATALOGUE = "CATALOGUE";

	/**
	 * Name of the structure <code>tl.threed.demo</code> defined by {@link TlThreedDemoFactory}.
	 */
	public static final String TL_THREED_DEMO_STRUCTURE = "tl.threed.demo";

	/**
	 * Lookup {@link Asset3D} type.
	 */
	public static com.top_logic.model.TLClass getAsset3DType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(TL_THREED_DEMO_STRUCTURE).getType(Asset3D.ASSET3D_TYPE);
	}

	/**
	 * Lookup {@link Asset3D#GLTF_URL_ATTR} of {@link Asset3D}.
	 */
	public static com.top_logic.model.TLProperty getGltfUrlAsset3DAttr() {
		return (com.top_logic.model.TLProperty) getAsset3DType().getPart(Asset3D.GLTF_URL_ATTR);
	}

	/**
	 * Lookup {@link Asset3D#JT_FILE_ATTR} of {@link Asset3D}.
	 */
	public static com.top_logic.model.TLProperty getJtFileAsset3DAttr() {
		return (com.top_logic.model.TLProperty) getAsset3DType().getPart(Asset3D.JT_FILE_ATTR);
	}

	/**
	 * Lookup {@link Asset3D#LAYOUT_POINT_ATTR} of {@link Asset3D}.
	 */
	public static com.top_logic.model.TLReference getLayoutPointAsset3DAttr() {
		return (com.top_logic.model.TLReference) getAsset3DType().getPart(Asset3D.LAYOUT_POINT_ATTR);
	}

	/**
	 * Lookup {@link Asset3D#NAME_ATTR} of {@link Asset3D}.
	 */
	public static com.top_logic.model.TLProperty getNameAsset3DAttr() {
		return (com.top_logic.model.TLProperty) getAsset3DType().getPart(Asset3D.NAME_ATTR);
	}

	/**
	 * Lookup {@link Asset3D#SNAPPING_POINTS_ATTR} of {@link Asset3D}.
	 */
	public static com.top_logic.model.TLReference getSnappingPointsAsset3DAttr() {
		return (com.top_logic.model.TLReference) getAsset3DType().getPart(Asset3D.SNAPPING_POINTS_ATTR);
	}

	/**
	 * Lookup {@link AssetCollection} type.
	 */
	public static com.top_logic.model.TLClass getAssetCollectionType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(TL_THREED_DEMO_STRUCTURE).getType(AssetCollection.ASSET_COLLECTION_TYPE);
	}

	/**
	 * Lookup {@link AssetCollection#ASSETS_ATTR} of {@link AssetCollection}.
	 */
	public static com.top_logic.model.TLReference getAssetsAssetCollectionAttr() {
		return (com.top_logic.model.TLReference) getAssetCollectionType().getPart(AssetCollection.ASSETS_ATTR);
	}

	/**
	 * Lookup {@link AssetCollection#SUB_FOLDERS_ATTR} of {@link AssetCollection}.
	 */
	public static com.top_logic.model.TLReference getSubFoldersAssetCollectionAttr() {
		return (com.top_logic.model.TLReference) getAssetCollectionType().getPart(AssetCollection.SUB_FOLDERS_ATTR);
	}

	/**
	 * Lookup {@link AssetCatalogue} type.
	 */
	public static com.top_logic.model.TLClass getAssetCatalogueType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(TL_THREED_DEMO_STRUCTURE).getType(AssetCatalogue.ASSET_CATALOGUE_TYPE);
	}

	/**
	 * Lookup {@link AssetFolder} type.
	 */
	public static com.top_logic.model.TLClass getAssetFolderType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(TL_THREED_DEMO_STRUCTURE).getType(AssetFolder.ASSET_FOLDER_TYPE);
	}

	/**
	 * Lookup {@link AssetFolder#NAME_ATTR} of {@link AssetFolder}.
	 */
	public static com.top_logic.model.TLProperty getNameAssetFolderAttr() {
		return (com.top_logic.model.TLProperty) getAssetFolderType().getPart(AssetFolder.NAME_ATTR);
	}

	/**
	 * Lookup {@link ConnectionPoint} type.
	 */
	public static com.top_logic.model.TLClass getConnectionPointType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(TL_THREED_DEMO_STRUCTURE).getType(ConnectionPoint.CONNECTION_POINT_TYPE);
	}

	/**
	 * Lookup {@link ConnectionPoint#CLASSIFIERS_ATTR} of {@link ConnectionPoint}.
	 */
	public static com.top_logic.model.TLProperty getClassifiersConnectionPointAttr() {
		return (com.top_logic.model.TLProperty) getConnectionPointType().getPart(ConnectionPoint.CLASSIFIERS_ATTR);
	}

	/**
	 * Lookup {@link ConnectionPoint#TX_ATTR} of {@link ConnectionPoint}.
	 */
	public static com.top_logic.model.TLProperty getTxConnectionPointAttr() {
		return (com.top_logic.model.TLProperty) getConnectionPointType().getPart(ConnectionPoint.TX_ATTR);
	}

	/**
	 * Lookup {@link ScenePart} type.
	 */
	public static com.top_logic.model.TLClass getScenePartType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(TL_THREED_DEMO_STRUCTURE).getType(ScenePart.SCENE_PART_TYPE);
	}

	/**
	 * Lookup {@link Node} type.
	 */
	public static com.top_logic.model.TLClass getNodeType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(TL_THREED_DEMO_STRUCTURE).getType(Node.NODE_TYPE);
	}

	/**
	 * Lookup {@link Node#ASSET_ATTR} of {@link Node}.
	 */
	public static com.top_logic.model.TLReference getAssetNodeAttr() {
		return (com.top_logic.model.TLReference) getNodeType().getPart(Node.ASSET_ATTR);
	}

	/**
	 * Lookup {@link Node#COLOR_ATTR} of {@link Node}.
	 */
	public static com.top_logic.model.TLProperty getColorNodeAttr() {
		return (com.top_logic.model.TLProperty) getNodeType().getPart(Node.COLOR_ATTR);
	}

	/**
	 * Lookup {@link Node#IMMUTABLE_ATTR} of {@link Node}.
	 */
	public static com.top_logic.model.TLProperty getImmutableNodeAttr() {
		return (com.top_logic.model.TLProperty) getNodeType().getPart(Node.IMMUTABLE_ATTR);
	}

	/**
	 * Lookup {@link Node#JT_FILE_ATTR} of {@link Node}.
	 */
	public static com.top_logic.model.TLProperty getJtFileNodeAttr() {
		return (com.top_logic.model.TLProperty) getNodeType().getPart(Node.JT_FILE_ATTR);
	}

	/**
	 * Lookup {@link Node#LAYER_ATTR} of {@link Node}.
	 */
	public static com.top_logic.model.TLProperty getLayerNodeAttr() {
		return (com.top_logic.model.TLProperty) getNodeType().getPart(Node.LAYER_ATTR);
	}

	/**
	 * Lookup {@link Node#NAME_ATTR} of {@link Node}.
	 */
	public static com.top_logic.model.TLProperty getNameNodeAttr() {
		return (com.top_logic.model.TLProperty) getNodeType().getPart(Node.NAME_ATTR);
	}

	/**
	 * Lookup {@link Node#TILE_ATTR} of {@link Node}.
	 */
	public static com.top_logic.model.TLProperty getTileNodeAttr() {
		return (com.top_logic.model.TLProperty) getNodeType().getPart(Node.TILE_ATTR);
	}

	/**
	 * Lookup {@link Node#TX_ATTR} of {@link Node}.
	 */
	public static com.top_logic.model.TLProperty getTxNodeAttr() {
		return (com.top_logic.model.TLProperty) getNodeType().getPart(Node.TX_ATTR);
	}

	/**
	 * Lookup {@link Assembly} type.
	 */
	public static com.top_logic.model.TLClass getAssemblyType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(TL_THREED_DEMO_STRUCTURE).getType(Assembly.ASSEMBLY_TYPE);
	}

	/**
	 * Lookup {@link Assembly#CHILDREN_ATTR} of {@link Assembly}.
	 */
	public static com.top_logic.model.TLReference getChildrenAssemblyAttr() {
		return (com.top_logic.model.TLReference) getAssemblyType().getPart(Assembly.CHILDREN_ATTR);
	}

	/**
	 * Lookup {@link Part} type.
	 */
	public static com.top_logic.model.TLClass getPartType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(TL_THREED_DEMO_STRUCTURE).getType(Part.PART_TYPE);
	}

	/**
	 * Lookup {@link Text} type.
	 */
	public static com.top_logic.model.TLClass getTextType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(TL_THREED_DEMO_STRUCTURE).getType(Text.TEXT_TYPE);
	}

	/**
	 * Lookup {@link Text#BACKGROUND_ATTR} of {@link Text}.
	 */
	public static com.top_logic.model.TLProperty getBackgroundTextAttr() {
		return (com.top_logic.model.TLProperty) getTextType().getPart(Text.BACKGROUND_ATTR);
	}

	/**
	 * Lookup {@link Text#COLOR_ATTR} of {@link Text}.
	 */
	public static com.top_logic.model.TLProperty getColorTextAttr() {
		return (com.top_logic.model.TLProperty) getTextType().getPart(Text.COLOR_ATTR);
	}

	/**
	 * Lookup {@link Text#FONT_SIZE_ATTR} of {@link Text}.
	 */
	public static com.top_logic.model.TLProperty getFontSizeTextAttr() {
		return (com.top_logic.model.TLProperty) getTextType().getPart(Text.FONT_SIZE_ATTR);
	}

	/**
	 * Lookup {@link Scene} type.
	 */
	public static com.top_logic.model.TLClass getSceneType() {
		return (com.top_logic.model.TLClass) com.top_logic.util.model.ModelService.getApplicationModel().getModule(TL_THREED_DEMO_STRUCTURE).getType(Scene.SCENE_TYPE);
	}

	/**
	 * Lookup {@link Scene#NAME_ATTR} of {@link Scene}.
	 */
	public static com.top_logic.model.TLProperty getNameSceneAttr() {
		return (com.top_logic.model.TLProperty) getSceneType().getPart(Scene.NAME_ATTR);
	}

	/**
	 * Lookup {@link Scene#ROOT_NODE_ATTR} of {@link Scene}.
	 */
	public static com.top_logic.model.TLReference getRootNodeSceneAttr() {
		return (com.top_logic.model.TLReference) getSceneType().getPart(Scene.ROOT_NODE_ATTR);
	}

	/**
	 * Name of type <code>Asset3D</code> in structure {@link #TL_THREED_DEMO_STRUCTURE}.
	 * 
	 * @deprecated Use {@link Asset3D#ASSET3D_TYPE}.
	 */
	@Deprecated
	public static final String ASSET3D_NODE = Asset3D.ASSET3D_TYPE;

	/**
	 * Storage table name of {@link #ASSET3D_NODE} objects.
	 */
	public static final String KO_NAME_ASSET3D = "GenericObject";

	/**
	 * Name of type <code>AssetCollection</code> in structure {@link #TL_THREED_DEMO_STRUCTURE}.
	 * 
	 * @deprecated Use {@link AssetCollection#ASSET_COLLECTION_TYPE}.
	 */
	@Deprecated
	public static final String ASSET_COLLECTION_NODE = AssetCollection.ASSET_COLLECTION_TYPE;

	/**
	 * Storage table name of {@link #ASSET_COLLECTION_NODE} objects.
	 */
	public static final String KO_NAME_ASSET_COLLECTION = "GenericObject";

	/**
	 * Name of type <code>AssetCatalogue</code> in structure {@link #TL_THREED_DEMO_STRUCTURE}.
	 * 
	 * @deprecated Use {@link AssetCatalogue#ASSET_CATALOGUE_TYPE}.
	 */
	@Deprecated
	public static final String ASSET_CATALOGUE_NODE = AssetCatalogue.ASSET_CATALOGUE_TYPE;

	/**
	 * Storage table name of {@link #ASSET_CATALOGUE_NODE} objects.
	 */
	public static final String KO_NAME_ASSET_CATALOGUE = "GenericObject";

	/**
	 * Name of type <code>AssetFolder</code> in structure {@link #TL_THREED_DEMO_STRUCTURE}.
	 * 
	 * @deprecated Use {@link AssetFolder#ASSET_FOLDER_TYPE}.
	 */
	@Deprecated
	public static final String ASSET_FOLDER_NODE = AssetFolder.ASSET_FOLDER_TYPE;

	/**
	 * Storage table name of {@link #ASSET_FOLDER_NODE} objects.
	 */
	public static final String KO_NAME_ASSET_FOLDER = "GenericObject";

	/**
	 * Name of type <code>ConnectionPoint</code> in structure {@link #TL_THREED_DEMO_STRUCTURE}.
	 * 
	 * @deprecated Use {@link ConnectionPoint#CONNECTION_POINT_TYPE}.
	 */
	@Deprecated
	public static final String CONNECTION_POINT_NODE = ConnectionPoint.CONNECTION_POINT_TYPE;

	/**
	 * Storage table name of {@link #CONNECTION_POINT_NODE} objects.
	 */
	public static final String KO_NAME_CONNECTION_POINT = "GenericObject";

	/**
	 * Name of type <code>ScenePart</code> in structure {@link #TL_THREED_DEMO_STRUCTURE}.
	 * 
	 * @deprecated Use {@link ScenePart#SCENE_PART_TYPE}.
	 */
	@Deprecated
	public static final String SCENE_PART_NODE = ScenePart.SCENE_PART_TYPE;

	/**
	 * Name of type <code>Node</code> in structure {@link #TL_THREED_DEMO_STRUCTURE}.
	 * 
	 * @deprecated Use {@link Node#NODE_TYPE}.
	 */
	@Deprecated
	public static final String NODE_NODE = Node.NODE_TYPE;

	/**
	 * Name of type <code>Assembly</code> in structure {@link #TL_THREED_DEMO_STRUCTURE}.
	 * 
	 * @deprecated Use {@link Assembly#ASSEMBLY_TYPE}.
	 */
	@Deprecated
	public static final String ASSEMBLY_NODE = Assembly.ASSEMBLY_TYPE;

	/**
	 * Storage table name of {@link #ASSEMBLY_NODE} objects.
	 */
	public static final String KO_NAME_ASSEMBLY = "GenericObject";

	/**
	 * Name of type <code>Part</code> in structure {@link #TL_THREED_DEMO_STRUCTURE}.
	 * 
	 * @deprecated Use {@link Part#PART_TYPE}.
	 */
	@Deprecated
	public static final String PART_NODE = Part.PART_TYPE;

	/**
	 * Storage table name of {@link #PART_NODE} objects.
	 */
	public static final String KO_NAME_PART = "GenericObject";

	/**
	 * Name of type <code>Text</code> in structure {@link #TL_THREED_DEMO_STRUCTURE}.
	 * 
	 * @deprecated Use {@link Text#TEXT_TYPE}.
	 */
	@Deprecated
	public static final String TEXT_NODE = Text.TEXT_TYPE;

	/**
	 * Storage table name of {@link #TEXT_NODE} objects.
	 */
	public static final String KO_NAME_TEXT = "GenericObject";

	/**
	 * Name of type <code>Scene</code> in structure {@link #TL_THREED_DEMO_STRUCTURE}.
	 * 
	 * @deprecated Use {@link Scene#SCENE_TYPE}.
	 */
	@Deprecated
	public static final String SCENE_NODE = Scene.SCENE_TYPE;

	/**
	 * Storage table name of {@link #SCENE_NODE} objects.
	 */
	public static final String KO_NAME_SCENE = "GenericObject";

	/**
	 * Singleton <code>CATALOGUE</code>.
	 */
	public AssetCatalogue getCatalogueSingleton() {
		return (AssetCatalogue) lookupSingleton(SINGLETON_CATALOGUE);
	}

	/**
	 * Singleton <code>CATALOGUE</code> on given branch.
	 */
	public AssetCatalogue getCatalogueSingleton(com.top_logic.knowledge.service.Branch requestedBranch) {
		return (AssetCatalogue) lookupSingleton(SINGLETON_CATALOGUE, requestedBranch);
	}

	/**
	 * Singleton <code>CATALOGUE</code> on given branch in given revision.
	 */
	public AssetCatalogue getCatalogueSingleton(com.top_logic.knowledge.service.Branch requestedBranch, com.top_logic.knowledge.service.Revision historyContext) {
		return (AssetCatalogue) lookupSingleton(SINGLETON_CATALOGUE, requestedBranch, historyContext);
	}


	/**
	 * Create an instance of {@link Asset3D} type.
	 */
	public final Asset3D createAsset3D(com.top_logic.model.TLObject context) {
		return (Asset3D) createObject(getAsset3DType(), context);
	}

	/**
	 * Create an instance of {@link Asset3D} type.
	 */
	public final Asset3D createAsset3D() {
		return createAsset3D(null);
	}

	/**
	 * Create an instance of {@link AssetCollection} type.
	 */
	public final AssetCollection createAssetCollection(com.top_logic.model.TLObject context) {
		return (AssetCollection) createObject(getAssetCollectionType(), context);
	}

	/**
	 * Create an instance of {@link AssetCollection} type.
	 */
	public final AssetCollection createAssetCollection() {
		return createAssetCollection(null);
	}

	/**
	 * Create an instance of {@link AssetCatalogue} type.
	 */
	public final AssetCatalogue createAssetCatalogue(com.top_logic.model.TLObject context) {
		return (AssetCatalogue) createObject(getAssetCatalogueType(), context);
	}

	/**
	 * Create an instance of {@link AssetCatalogue} type.
	 */
	public final AssetCatalogue createAssetCatalogue() {
		return createAssetCatalogue(null);
	}

	/**
	 * Create an instance of {@link AssetFolder} type.
	 */
	public final AssetFolder createAssetFolder(com.top_logic.model.TLObject context) {
		return (AssetFolder) createObject(getAssetFolderType(), context);
	}

	/**
	 * Create an instance of {@link AssetFolder} type.
	 */
	public final AssetFolder createAssetFolder() {
		return createAssetFolder(null);
	}

	/**
	 * Create an instance of {@link ConnectionPoint} type.
	 */
	public final ConnectionPoint createConnectionPoint(com.top_logic.model.TLObject context) {
		return (ConnectionPoint) createObject(getConnectionPointType(), context);
	}

	/**
	 * Create an instance of {@link ConnectionPoint} type.
	 */
	public final ConnectionPoint createConnectionPoint() {
		return createConnectionPoint(null);
	}

	/**
	 * Create an instance of {@link Assembly} type.
	 */
	public final Assembly createAssembly(com.top_logic.model.TLObject context) {
		return (Assembly) createObject(getAssemblyType(), context);
	}

	/**
	 * Create an instance of {@link Assembly} type.
	 */
	public final Assembly createAssembly() {
		return createAssembly(null);
	}

	/**
	 * Create an instance of {@link Part} type.
	 */
	public final Part createPart(com.top_logic.model.TLObject context) {
		return (Part) createObject(getPartType(), context);
	}

	/**
	 * Create an instance of {@link Part} type.
	 */
	public final Part createPart() {
		return createPart(null);
	}

	/**
	 * Create an instance of {@link Text} type.
	 */
	public final Text createText(com.top_logic.model.TLObject context) {
		return (Text) createObject(getTextType(), context);
	}

	/**
	 * Create an instance of {@link Text} type.
	 */
	public final Text createText() {
		return createText(null);
	}

	/**
	 * Create an instance of {@link Scene} type.
	 */
	public final Scene createScene(com.top_logic.model.TLObject context) {
		return (Scene) createObject(getSceneType(), context);
	}

	/**
	 * Create an instance of {@link Scene} type.
	 */
	public final Scene createScene() {
		return createScene(null);
	}

	/**
	 * The singleton instance of {@link TlThreedDemoFactory}.
	 */
	public static TlThreedDemoFactory getInstance() {
		return (TlThreedDemoFactory) com.top_logic.element.model.DynamicModelService.getFactoryFor(TL_THREED_DEMO_STRUCTURE);
	}
}
