/*
 * SPDX-FileCopyrightText: 2025 (c) Business Operation Systems GmbH <info@top-logic.com>
 * 
 * SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-BOS-TopLogic-1.0
 */
package com.top_logic.threed.core.model;

/**
 * Factory for <code>tl.threed.core</code> objects.
 * 
 * <p>
 * Note: this is generated code. Do not modify. Instead, create a subclass and register this in the module system.
 * </p>
 * 
 * @author Automatically generated by {@link com.top_logic.element.model.generate.FactoryGenerator}
 */
public class TlThreedCoreFactory extends com.top_logic.element.meta.kbbased.AbstractElementFactory {

	/**
	 * Name of the structure <code>tl.threed.core</code> defined by {@link TlThreedCoreFactory}.
	 */
	public static final String TL_THREED_CORE_STRUCTURE = "tl.threed.core";

	/**
	 * Name of the data type <code>Transformation</code> in module {@value #TL_THREED_CORE_STRUCTURE}.
	 */
	public static final String TRANSFORMATION_TYPE = "Transformation";

	/**
	 * Lookup {@value #TRANSFORMATION_TYPE} data type.
	 */
	public static com.top_logic.model.TLPrimitive getTransformationType() {
		return (com.top_logic.model.TLPrimitive) com.top_logic.util.model.ModelService.getApplicationModel().getModule(TL_THREED_CORE_STRUCTURE).getType(TRANSFORMATION_TYPE);
	}


	/**
	 * The singleton instance of {@link TlThreedCoreFactory}.
	 */
	public static TlThreedCoreFactory getInstance() {
		return (TlThreedCoreFactory) com.top_logic.element.model.DynamicModelService.getFactoryFor(TL_THREED_CORE_STRUCTURE);
	}
}
